### ISSUE TITLE
Dependencies for Fedora (25) compile instructions are out of date

### ISSUE THREAD

**Issue by axelsimon** [clementine-player/Clementine#5607]
### System information
- Operating System: FC25

Hi,
The wiki [suggests installing](https://github.com/clementine-player/Clementine/wiki/Compiling-from-Source):
```
su -c "yum install gcc-c++ liblastfm-devel taglib-devel gettext boost-devel \
    qt-devel cmake gstreamer1-devel gstreamer1-plugins-base-devel glew-devel \
    libgpod-devel qjson-devel libplist-devel \
    usbmuxd-devel libmtp-devel protobuf-devel protobuf-compiler cryptopp-devel \
    libcdio-devel fftw-devel sparsehash-devel sqlite-devel \
    pulseaudio-libs-devel libqtwebkit-dev sha2-devel libchromaprint-dev qca-devel"
```

But `usbmuxd-devel`, `libchromaprint-dev` and `libqtwebkit-dev` don't exist in the Fedora 25 repos.
However,`libusbmuxd-devel` and `libchromaprint-devel` do, so that's good. But no `libqtwebkit` of any kind is to be found.

Another, smaller issue, is that `yum` has been replaced by `dnf`.
I suggest changing that dependencies install list to:

```
su -c "dnf install gcc-c++ liblastfm-devel taglib-devel gettext boost-devel \
    qt-devel cmake gstreamer1-devel gstreamer1-plugins-base-devel glew-devel \
    libgpod-devel qjson-devel libplist-devel \
    libusbmuxd-devel libmtp-devel protobuf-devel protobuf-compiler cryptopp-devel \
    libcdio-devel fftw-devel sparsehash-devel sqlite-devel \
    pulseaudio-libs-devel sha2-devel libchromaprint-devel qca-devel"
```
Considering  that in the actual list of dependencies on the wiki page (not the apt/yum examples but the list above), there is no mention of QtWebkit, I have not put in the above suggested `dnf install` command.

Hope this helps.

**Comment by hatstand** [comment]
Fixed, thanks.

**Comment by axelsimon** [comment]
Cool, thanks. And quick too!
However, I'm still not sure why libqtwebkit(-dev) is a dependency 🙂
