### ISSUE TITLE
Unable to resolve host spotify.clementine-player.org

### ISSUE THREAD

**Issue by jbroadus** [clementine-player/Clementine#6562]
; <<>> DiG 9.11.14-RedHat-9.11.14-2.fc31 <<>> spotify.clementine-player.org @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44821
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;spotify.clementine-player.org.	IN	A

;; AUTHORITY SECTION:
clementine-player.org.	1799	IN	SOA	joel.ns.cloudflare.com. dns.cloudflare.com. 2033204518 10000 2400 604800 3600

;; Query time: 63 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Fri Jan 31 22:53:05 PST 2020
;; MSG SIZE  rcvd: 120

**Comment by hatstand** [comment]
Fixed

**Comment by jbroadus** [comment]
Host resolves now, but the blob download still isn't working:

$ curl https://spotify.clementine-player.org/version16-64bit/blob
<!doctype html><body>
<div><a href="https://www.googleapis.com/download/storage/v1/b/builds.clementine-player.org/o/version16-64bit%2Fblob?generation=1580567215944396&alt=media"></a></div><div><a href="https://www.googleapis.com/download/storage/v1/b/builds.clementine-player.org/o/version16-64bit%2Fblob.sha512?generation=1580567216068289&alt=media">.sha512</a></div></body>

**Comment by hatstand** [comment]
Should actually work now.
